blank_issues_enabled: true
contact_links:
  - name: VpnCloud Documentation
    url: https://vpncloud.ddswd.de/docs
    about: Pleae check the documentation before asking how things work.
  - name: VpnCloud Discussion Group on GitHub
    url: https://github.com/dswd/vpncloud/discussions
    about: Please discuss or ask anything there that is **not an issue**.
