name: vpncloud
version: 2.1.0
summary: Peer-to-peer VPN
description: |
  VpnCloud is a high performance peer-to-peer mesh VPN over UDP supporting strong encryption, 
  NAT traversal and a simple configuration. It establishes a fully-meshed self-healing VPN
  network in a peer-to-peer manner with strong end-to-end encryption based on elliptic curve
  keys and AES-256. VpnCloud creates a virtual network interface on the host and forwards all
  received data via UDP to the destination. It can work on TUN devices (IP based) and TAP 
  devices (Ethernet based).

confinement: devmode

parts:
  vpncloud:
    plugin: dump
    source: vpncloud_${SNAPCRAFT_PROJECT_VERSION}_amd64.deb

apps:
  vpncloud:
    command: usr/bin/vpncloud
